id: PABD13797
initial_creation_type: input
source_metadata:
  title: Vajravidāraṇa Series
  language: en
  description: 'A series of texts related to the deity Vajravidāraṇa (rdo rje rnam
    ‘joms), a wrathful form of Vajrapāṇi:'
  volume:
    a1a7284cbe7e4c4d9afa78aaed450e52:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Dhāraṇī
created_at: '2022-03-01T06:33:31.554223'
last_modified_at: '2022-03-01T06:33:31.554229'
